### ISSUE TITLE
Add north arrows and scale bars to map figures

### ISSUE THREAD

**Issue by lkoolik** [echo-air-model/echo-air#35]

**Comment by rosypctals** [comment]
I ran the model and it worked with the matplotlib scalebar! After running pip list>test, this is what is inside my list.txt:

Package             Version
------------------- -----------
attrs               21.4.0
certifi             2021.10.8
click               8.1.2
click-plugins       1.1.1
cligj               0.7.2
cycler              0.11.0
DateTime            4.5
Fiona               1.8.21
fonttools           4.32.0
geopandas           0.10.2
kiwisolver          1.4.2
matplotlib          3.5.1
matplotlib-scalebar 0.8.1
munch               2.5.0
numpy               1.22.3
packaging           21.3
pandas              1.4.2
pathlib             1.0.1
Pillow              9.1.0
pip                 20.2.3
pyarrow             7.0.0
pyparsing           3.0.8
pyproj              3.3.0
python-dateutil     2.8.2
pytz                2022.1
Rtree               1.0.0
scipy               1.8.0
seaborn             0.11.2
setuptools          49.2.1
Shapely             1.8.1.post1
six                 1.16.0
zope.interface      5.4.0
